replication_factor = 1
consistency_mode = "consistent"

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/snapshots"
metadata_fsync = true
data_fsync = false
disable_scrub = false
use_local_tz = false
metadata_auto_snapshot_interval = "6h"

db_engine = "lmdb"

block_size = "1M"
block_ram_buffer_max = "256MiB"

lmdb_map_size = "1T"

compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_bind_outgoing = false
rpc_public_addr = "localhost:3901"
rpc_secret = "7f2e8d9c4a6b1e5f3c8d2a7b9e4f6c1d8a3e7b2f5c9d6a1e4b8f2c7d3a6e9b5c"

allow_world_readable_secrets = false

allow_punycode = false

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".s3.web.garage.localhost"
add_host_to_metrics = true

[admin]
api_bind_addr = "[::]:3903"
admin_token = "F876F9A2E9BA1DE148E55D4D12A8F"
metrics_token = "FD40E71775216595621D33001349C6B4"