[package]
name = "server"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "api","entity", "files-api", "migration", "reports", "services"]
exclude = [ "migration" ]

[dependencies]
api = { path = "api"}
services = { path = "services"}
axum = "0.8.4"
sqlx = "0.8.6"
tokio = { version = "1.45.1", features = ["full"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
sea-orm = { version = "1.1.12", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros", "debug-print"]}
redis = { version = "0.31.0", features = ["tokio-native-tls-comp"]}
tower-http = { version = "0.6.6", features = ["cors"]}
tower = "0.5.2"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.94.0", features = ["behavior-version-latest"]}
futures = "0.3.31"
tokio-stream = { version = "0.1.17", features = ["sync"]}
serde_json = "1.0.140"

[profile.release]
opt-level = 3