use entity::contractors;
use sea_orm_migration::{prelude::*, sea_orm::{ActiveValue::Set, EntityTrait}};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Replace the sample below with your own migration scripts
        let db = manager.get_connection();

        let all_contractors = vec![
            contractors::ActiveModel {
                name: Set("CTG Construction".to_string()),
                email_address: Set("ctg@gmail.com".to_string()),
                address_street: Set("Purok 1".to_string()),
                address_barangay: Set("San Jose".to_string()),
                address_municipality: Set("Pagadian City".to_string()),
                address_province: Set("Zamboanga del Sur".to_string()),
                contact_full_name: Set("Juan Luna".to_string()),
                contact_position: Set("Taker".to_string()),
                contact_number: Set("09506636243".to_string()),
                // Add all other fields explicitly here if they are part of your ActiveModel
                // For example, if you have a `notes` field:
                // notes: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("ALZ Construction".to_string()),
                email_address: Set("".to_string()), // No email provided, so empty string
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("GAF TRADING & CONST".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Alajeño Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("MOLROW CONSTRUCTION".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("DM Ventures".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("St. Joseph Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("JAMT Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Johairy Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("RSQ Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Ashlar Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("LC Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Glenson Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Ammara Strukture Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Aradel Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("AJT Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Victer Construction & Devt, OPC".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Domphil Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Jenrich Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Maqueserg Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Long Island Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("H. Jade Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("KS Agad Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("MG Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Five Star Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("ZMS Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("JZL Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("NRMM Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Genetian Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("M&L Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("OG Santos Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Pagadian Aggregates".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("GCMG Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Abdulbasit Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("JH Pameron Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("CDTech Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("ILLANA Bay Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("MJMARRI Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Diaka Kunstrukt".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("ILLAN Construction & Ent.".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("GCMG (Garcia) Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Genetian (Alex Co)".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("GCMG (Gumilao)".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Pyramid Builders".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Danton Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Diaca Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("AFS Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("AM Tabayag Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Diplahan Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Jimwen Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("Ammara Construction".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set("BADSBRO".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set(" MDS CONSTRUCTION & ENTERPRISES".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set(" SEVERS CONSTRUCTION & SUPPLIES & REALTY DEVELOPMENT".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set(" SALUGVALLEY ENTERPRISES & DEVELOPMENT CORP.(SVDC)".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set(" 3L & JES".to_string()),
                email_address: Set("".to_string()),
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("".to_string()),
                address_province: Set("".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
            contractors::ActiveModel {
                name: Set(" LONG ISLAND BUILDERS & CONST.".to_string()),
                email_address: Set("".to_string()), // Explicitly set to empty string
                address_street: Set("".to_string()),
                address_barangay: Set("".to_string()),
                address_municipality: Set("Ipil".to_string()),
                address_province: Set("Zamboanga Sebugay".to_string()),
                contact_full_name: Set("".to_string()),
                contact_position: Set("".to_string()),
                contact_number: Set("".to_string()),
                ..Default::default()
            },
        ];

        contractors::Entity::insert_many(all_contractors).exec(db).await.unwrap();

        Ok(())
    }
}